modrinth_api: "https://api.modrinth.com/v2"
mc_version: "1.20.1"
mod_loader: "fabric"
mods:
# server-side
  - "fabric-api"
  - "ferrite-core"
  - "lithium"
  - "memoryleakfix"
  - "starlight"
  - "carpet"
  - "krypton"
  - "mixintrace"
  - "no-chat-reports"
  - "alternate-current"
# client-side
  - "dynamic-fps"
  - "entityculling"
  - "fadeless"
  - "sodium"
  - "better-mount-hud"
  - "indium"
  - "fabrishot"
  - "iris"
  - "cloth-config"
  - "moreculling"
  - "reeses-sodium-options"
  - "modmenu"
  - "morechathistory"
  - "modelfix"
  - "borderless-mining"
  - "Fastquit"
  - "exordium"
  - "appleskin"
  - "language-reload"
  - "replaymod"
  - "immediatelyfast"
  - "ebe"
# extra mods:
# decoration
#   - "3dskinlayers"
#   - "continuity"
#   - "fallingleaves"
#   - "eating-animation"
#   - "lambdabettergrass"
#   - "lambdynamiclights"
#   - "presence-footsteps"
# gui
#   - "sodium-extra"
#   - "inventory-profiles-next"
#   - "better-ping-display-fabric"
# performance
#   - "c2me-fabric"
# misc
#   - "bobby"
